name: clement-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - scipy
  - scikit-image
  - pyqt=5
  - pyinstaller
  - numexpr
  - pip
  - git
  - pip:
    - mrcfile
    - read-lif
    - git+https://github.com/pyqtgraph/pyqtgraph.git@develop

