name: clement
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - scipy
  - scikit-image
  - pyqt=5
  - pyqtgraph
  - pyinstaller
  - numexpr
  - pip
  - git
  - pip:
    - mrcfile
    - read-lif

