name: clem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - scikit-image
  - pyqt=5
  - pyinstaller
  - numexpr
  - pip
  - git
  - pyyaml
  - scikit-learn
  - pip:
    - mrcfile
    - read-lif==0.3.1
    #- git+https://github.com/pyqtgraph/pyqtgraph.git@develop
    - pyqtgraph
    - uncertainties
